version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    # ephemeral volume inside the container
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    command: /app/backend/entrypoint.sh
    environment:
      PYTHONPATH: /app/backend
      # If you had DB credentials, you'd need them here
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
