version: '3.8'
services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/backend
    env_file:
      - ./app/backend/.env.prod
    depends_on:
      - db

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - ./app/backend/.env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: