version: '3.8'
services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    command: /app/backend/entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - ./app/backend:/app/backend
    environment:
      - PYTHONPATH=/app/backend
    env_file:
      - ./app/backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:latest
    env_file:
      - ./app/backend/.env.postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: