image:
  backend: "ramiroaguero/craftechtest:backend-v1.16.17"
  frontend: "ramiroaguero/craftechtest:frontend-v1.16.30"
  pullPolicy: Always

service:
  type: LoadBalancer
  backendPort: 8000
  frontendPort: 3000

database:
  name: django_db
  user: admin
  password: supersecret
  host: postgres-service
  port: "5432"

env:
  DJANGO_ALLOWED_HOSTS: "backend-service,backend-service.default.svc.cluster.local,a4db59dda552049758b4e2cb631de79d-1080103396.us-east-1.elb.amazonaws.com,a50ec3b714a554d65a17dbcd37703451-475530952.us-east-1.elb.amazonaws.com"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000,http://a4db59dda552049758b4e2cb631de79d-1080103396.us-east-1.elb.amazonaws.com,http://a50ec3b714a554d65a17dbcd37703451-475530952.us-east-1.elb.amazonaws.com"
  DEBUG: "False"

serviceAccount:
  create: true
  name: django-service-account
  automount: true
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::037380703489:role/eksctl-craftech-cluster-cluster-ServiceRole-j7EkuXzGfcfE"

ingress:
  enabled: false

secretKey: "your-django-secret-key"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
