image:
  backend: "ramiroaguero/craftechtest:backend-1.17.6"
  frontend: "ramiroaguero/craftechtest:frontend-1.17.4"
  pullPolicy: Always

service:
  type: LoadBalancer
  backendPort: 8000
  frontendPort: 3000

database:
  name: django_db
  user: admin
  password: supersecret
  host: postgres-service
  port: "5432"

env:
  DJANGO_ALLOWED_HOSTS: "backend-service,backend-service.default.svc.cluster.local,aaffc0a22feb44a18be60ad86a9d24b1-935174219.us-east-1.elb.amazonaws.com"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000,http://a1ea82fa5c25a46e4a572f1871350ccb-1392024633.us-east-1.elb.amazonaws.com:3000"
  REACT_APP_BACKEND_URL: "http://aaffc0a22feb44a18be60ad86a9d24b1-935174219.us-east-1.elb.amazonaws.com:8000"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false
