image:
  backend: "ramiroaguero/backend:1.17.7"
  frontend: "ramiroaguero/frontend:1.17.7"
  pullPolicy: Always

service:
  type: LoadBalancer
  backendPort: 8000
  frontendPort: 3000

database:
  name: django_db
  user: admin
  password: supersecret
  host: postgres-service
  port: "5432"

env:
  DJANGO_ALLOWED_HOSTS: "backend-service,backend-service.default.svc.cluster.local,a36296300e9b941eb851c99d553e43f6-1459072743.us-east-1.elb.amazonaws.com"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000,http://af41c0d4453294d058038bbe1b7d3cc3-884279893.us-east-1.elb.amazonaws.com:3000"
  REACT_APP_BACKEND_URL: "http://a36296300e9b941eb851c99d553e43f6-1459072743.us-east-1.elb.amazonaws.com:8000"


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false
