apiVersion: v1
kind: ConfigMap
metadata:
  name: django-env
data:
  DATABASE_URL: "postgres://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
  DJANGO_SETTINGS_MODULE: "core.settings"
  DEBUG: "1"
  DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1 [::1]"

  SQL_ENGINE: "django.db.backends.postgresql"
  SQL_DATABASE: "{{ .Values.database.name }}"
  SQL_USER: "{{ .Values.database.user }}"
  SQL_PASSWORD: "{{ .Values.database.password }}"
  SQL_HOST: "{{ .Values.database.host }}"
  SQL_PORT: "{{ .Values.database.port }}"
  DATABASE: "postgres"
