name: Craftech Pipeline

on:
  push:
    branches:
      - main
      - Development
      - Feature-Prueba3
    paths:
      - 'Prueba3/index.html'
      - '.github/workflows/**'
      - 'Dockerfile'

env:
  DOCKER_IMAGE: ramiroaguero/craftech

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Prueba3
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    
    steps:
      - name: Deploy latest version
        run: |
          docker-compose down
          docker system prune -af
          docker-compose pull
          docker-compose up -d